### ISSUE TITLE
Unable to register new users

### ISSUE THREAD

**Issue by kkoorndyk** [docdoku/docdoku-plm#1082]
I have a new installation of the stable release using Glassfish 4.0 on Ubuntu Server 16.04.
I followed the installation directions on the wiki and confirmed all of the settings are correct.

When attempting to create/register the first user in DocDokuPLM, I receive the following error in the browser:
```
Error
javax.servlet.ServletException: Login failed
```

The following is from the server log:
```
[2016-12-15T12:17:14.236-0500] [glassfish 4.0] [WARNING] [web.login.failed] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=24 _ThreadName=http-listener-1(5)] [timeMillis: 1481822234236] [levelValue: 900] [[
  WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for redacted.]]

[2016-12-15T12:17:14.237-0500] [glassfish 4.0] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=24 _ThreadName=http-listener-1(5)] [timeMillis: 1481822234237] [levelValue: 900] [[
  #{accountBean.register}: javax.servlet.ServletException: Login failed
javax.faces.FacesException: #{accountBean.register}: javax.servlet.ServletException: Login failed
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:357)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:260)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:246)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:191)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:168)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:189)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:838)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:115)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:55)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:135)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:564)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:544)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.faces.el.EvaluationException: javax.servlet.ServletException: Login failed
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
        ... 39 more
Caused by: javax.servlet.ServletException: Login failed
        at org.apache.catalina.authenticator.AuthenticatorBase.doLogin(AuthenticatorBase.java:959)
        at org.apache.catalina.authenticator.AuthenticatorBase.login(AuthenticatorBase.java:939)
        at org.apache.catalina.connector.Request.login(Request.java:2245)
        at org.apache.catalina.connector.Request.login(Request.java:2224)
        at org.apache.catalina.connector.RequestFacade.login(RequestFacade.java:1113)
        at com.docdoku.server.jsf.actions.AccountBean.register(AccountBean.java:76)
        at com.docdoku.server.jsf.actions.AccountBean$Proxy$_$$_WeldClientProxy.register(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.el.parser.AstValue.invoke(AstValue.java:275)
        at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        ... 40 more
]]
```

However, I receive the account creation successful email and when I query the database the ACCOUNT, CREDENTIALS and USERGROUPMAPPING tables have an entry, so it appears that something worked.

If I attempt to log in using that username after the failure, I receive the following error in the browser:
`DocdokuPLM failed to connect
`

And the following in the server log:
```
[2016-12-15T12:27:44.213-0500] [glassfish 4.0] [WARNING] [web.login.failed] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=21 _ThreadName=http-listener-1(2)] [timeMillis: 1481822864213] [levelValue: 900] [[
  WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for redacted.]]

[2016-12-15T12:27:44.214-0500] [glassfish 4.0] [WARNING] [] [com.docdoku.server.jsf.actions.ConnectionBean] [tid: _ThreadID=21 _ThreadName=http-listener-1(2)] [timeMillis: 1481822864214] [levelValue: 900] [[
  The user 'redacted' failed to login]]

```

Any ideas what may be wrong?

**Comment by mguimard** [comment]
Hi, 

The wiki is up to date with dev branch, and authentication has been rewrote since latest stable release. Then I think you're missing some configuration steps.

Please follow these instructions (security section) : https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide/d1f425c92da1a2a2261cbde50f4e0b269d6e0a3a#security, then add to `<domaindir>/config/login.conf` the following lines:

    docdokuRealm {
        com.sun.enterprise.security.ee.auth.login.JDBCLoginModule required; 
    };

Restart the server and it should be ok

**Comment by kkoorndyk** [comment]
That did the trick.  Thanks so much for the quick response!
