### ISSUE TITLE
Build fail npm

### ISSUE THREAD

**Issue by sah4ez** [docdoku/docdoku-plm#1105]
When I build project, I have error:
~/docdoku-plm/docdoku-api-js/npm-debug.log
```15 silly lifecycle docdoku-api-js@1.0.0~build: Args: [ '-c', 'grunt build' ]
16 info lifecycle docdoku-api-js@1.0.0~build: Failed to exec build script
17 verbose stack Error: docdoku-api-js@1.0.0 build: `grunt build`
17 verbose stack spawn ENOENT
17 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
17 verbose stack     at emitTwo (events.js:87:13)
17 verbose stack     at ChildProcess.emit (events.js:172:7)
17 verbose stack     at maybeClose (internal/child_process.js:821:16)
17 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
18 verbose pkgid docdoku-api-js@1.0.0
19 verbose cwd /home/sah4ez/git/docdoku-plm/docdoku-api-js
20 error Linux 4.8.0-56-generic
21 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
22 error node v4.2.6
23 error npm  v3.5.2
24 error file sh
25 error code ELIFECYCLE
26 error errno ENOENT
27 error syscall spawn
28 error docdoku-api-js@1.0.0 build: `grunt build`
28 error spawn ENOENT
29 error Failed at the docdoku-api-js@1.0.0 build script 'grunt build'.
29 error Make sure you have the latest version of node.js and npm installed.
29 error If you do, this is most likely a problem with the docdoku-api-js package,
29 error not with npm itself.
29 error Tell the author that this fails on your system:
29 error     grunt build
29 error You can get information on how to open an issue for this project with:
29 error     npm bugs docdoku-api-js
29 error Or if that isn't available, you can get their info via:
29 error     npm owner ls docdoku-api-js
29 error There is likely additional logging output above.
30 verbose exit [ 1, true ]```

And output:

``` bash
user@pc:~/docdoku-plm-docker$ npm bugs docdoku-api-js
npm ERR! Linux 4.8.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "docdoku-api-js"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/docdoku-api-js
npm ERR! 404 
npm ERR! 404  'docdoku-api-js' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/docdoku-plm-docker/npm-debug.log

```

**Comment by mguimard** [comment]
Hard to find out from the logs, please tell me:
 - which branch are you trying to build
 - which command did you run to build the project ?

**Comment by mguimard** [comment]
Did you install grunt-cli ?

    [sudo] npm install -g grunt-cli

**Comment by sah4ez** [comment]
I run command from:
https://github.com/docdoku/docdoku-plm-docker/commit/616dc2af985ffb3a6989d7c48ad74ee413dd3bc1 for build backend. But I installed grunt instead grunt-cli...

**Comment by sah4ez** [comment]
I install grunt-cli and all build.
