### ISSUE TITLE
[login] Unable to login

### ISSUE THREAD

**Issue by Cissoubaka** [docdoku/docdoku-plm#1119]
in version 2.0
I can create account, seen them on the mysql database, but I can't login

I have those error on the log :

```
[2017-10-18T21:30:41.866+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.system.container.web.com.sun.web.security] [tid: _ThreadID=28 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1508355041866] [levelValue: 900] [[
  WEB9102: Web Login Failed: com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for test3.]]

[2017-10-18T21:30:41.888+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=28 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1508355041888] [levelValue: 900] [[
  #{accountBean.register}: javax.servlet.ServletException: Login failed
javax.faces.FacesException: #{accountBean.register}: javax.servlet.ServletException: Login failed


[2017-10-18T21:30:41.895+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=28 _ThreadName=http-thread-pool::http-listener-1(5)] [timeMillis: 1508355041895] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
javax.servlet.ServletException: Login failed
	at org.apache.catalina.authenticator.AuthenticatorBase.doLogin(AuthenticatorBase.java:956)
	at org.apache.catalina.authenticator.AuthenticatorBase.login(AuthenticatorBase.java:936)

```

**Comment by florentgarin** [comment]
please use version 2.5 which is the version intended to run on Payara 4.1
