### ISSUE TITLE
[CAD File] Conversion infinite on .obj file

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-plm#1121]
[obj_file.zip](https://github.com/docdoku/docdoku-plm/files/1401064/obj_file.zip)
After uploading a .obj of 9Mo, the conversion is pending indefinitely and the server return an exception :

[2017-10-19T10:10:28.920+0200] [Payara 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=143 _ThreadName=__ejb-thread-pool4] [timeMillis: 1508400628920] [levelValue: 900] [[
  
javax.ejb.EJBException
	at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:750)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:700)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:505)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4538)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2019)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at jdk.nashorn.internal.scripts.JO4.allocate(Unknown Source)
	at java.lang.invoke.LambdaForm$DMH/109915725.invokeStatic_L_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/1842201329.invokeExact_MT(LambdaForm$MH)
	at jdk.nashorn.internal.runtime.AllocationStrategy.allocate(AllocationStrategy.java:127)
	at jdk.nashorn.internal.runtime.RecompilableScriptFunctionData.allocate(RecompilableScriptFunctionData.java:378)
	at jdk.nashorn.internal.runtime.ScriptFunction.allocate(ScriptFunction.java:525)
	at java.lang.invoke.LambdaForm$DMH/1463801669.invokeVirtual_L_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/533206118.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/326549596.delegate(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/533735300.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/429462114.linkToCallSite(LambdaForm$MH)
	at jdk.nashorn.internal.scripts.Script$Recompilation$106$29405$\^eval\_.clone-2(<eval>:1579)
	at java.lang.invoke.LambdaForm$DMH/1830908236.invokeStatic_LL_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/776541138.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/1343441044.delegate(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/1696282916.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/1665839126.linkToCallSite(LambdaForm$MH)
	at jdk.nashorn.internal.scripts.Script$Recompilation$187$190992AAA$\^eval\_.merge-1(<eval>:10004)
	at java.lang.invoke.LambdaForm$DMH/683287027.invokeStatic_L5_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/657762067.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/404550912.exactInvoker(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/898550272.linkToCallSite(LambdaForm$MH)
	at jdk.nashorn.internal.scripts.Script$Recompilation$186$590179AAA$\^eval\_.merge-3(<eval>:25862)
	at java.lang.invoke.LambdaForm$DMH/683287027.invokeStatic_L5_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/743064601.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/320076317.exactInvoker(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/1772455715.linkToCallSite(LambdaForm$MH)
	at jdk.nashorn.internal.scripts.Script$Recompilation$185$705ADA$\^eval\_.calculateBox#L:31(<eval>:32)
	at java.lang.invoke.LambdaForm$DMH/277630005.invokeStatic_L3_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/574148672.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/428055143.exactInvoker(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$reinvoker/1400664660.dontInline(LambdaForm$reinvoker)
]]

**Comment by mguimard** [comment]
Please share that obj file

**Comment by hobywhan** [comment]
Added file

**Comment by mguimard** [comment]
>"Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded"

The conversion is done in nashorn (js running in the jvm), and not very efficient in terms of memory. We have to find a better way to handle large files. What was the -Xmx value ?

Try to increase the -Xmx value and launch again the conversion.

**Comment by mguimard** [comment]
Many memory improvements have been made, closing issue, please reopen if needed.
