### ISSUE TITLE
Unable to access the Webserver 

### ISSUE THREAD

**Issue by DRDL** [docdoku/docdoku-plm#1166]
[2018-07-24T10:53:23.882+0530] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1532409803882] [levelValue: 800] [[
  JVM invocation command line:
/usr/lib/jvm/java-8-oracle/bin/java
-cp
/opt/payara41/glassfish/modules/glassfish.jar
-Xmx512m
-client
-javaagent:/opt/payara41/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/opt/payara41/glassfish/domains/domain1/config/cacerts.jks
-Djdk.tls.rejectClientInitiatedRenegotiation=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/opt/payara41/glassfish/modules/autostart/
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/opt/payara41/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/opt/payara41/glassfish/modules/endorsed:/opt/payara41/glassfish/lib/endorsed
-Djava.security.policy=/opt/payara41/glassfish/domains/domain1/config/server.policy
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Djavax.net.ssl.keyStore=/opt/payara41/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/opt/payara41/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/opt/payara41/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false
-Dosgi.shell.telnet.ip=127.0.0.1
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/lib/jvm/java-8-oracle/lib/ext:/usr/lib/jvm/java-8-oracle/jre/lib/ext:/opt/payara41/glassfish/domains/domain1/lib/ext
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/opt/payara41/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/opt/payara41/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/opt/payara41/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/opt/payara41/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain
-watchdog
false]]

[2018-07-24T10:53:39.163+0530] [Payara 4.1] [INFO] [NCLS-LOGGING-00009] [javax.enterprise.logging] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1532409818413] [timeMillis: 1532409819163] [levelValue: 800] [[
  Running Payara Version: Payara Server Blue  4.1.2.181 #badassfish (build 220)]]

[2018-07-24T10:53:39.171+0530] [Payara 4.1] [INFO] [NCLS-LOGGING-00010] [javax.enterprise.logging] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1532409818413] [timeMillis: 1532409819171] [levelValue: 800] [[
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter]]

[2018-07-24T10:53:40.006+0530] [Payara 4.1] [INFO] [] [org.hibernate.validator.internal.util.Version] [tid: _ThreadID=16 _ThreadName=RunLevelControllerThread-1532409818413] [timeMillis: 1532409820006] [levelValue: 800] [[
  HV000001: Hibernate Validator 5.2.4.Final]]

[2018-07-24T10:53:41.646+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=23 _ThreadName=RunLevelControllerThread-1532409819580] [timeMillis: 1532409821646] [levelValue: 800] [[
  Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2018-07-24T10:53:41.724+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=23 _ThreadName=RunLevelControllerThread-1532409819580] [timeMillis: 1532409821724] [levelValue: 800] [[
  Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.]]

[2018-07-24T10:53:41.757+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01115] [javax.enterprise.system.core.security] [tid: _ThreadID=23 _ThreadName=RunLevelControllerThread-1532409819580] [timeMillis: 1532409821757] [levelValue: 800] [[
  Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.]]

[2018-07-24T10:53:42.321+0530] [Payara 4.1] [INFO] [SEC-SVCS-00100] [javax.enterprise.security.services] [tid: _ThreadID=23 _ThreadName=RunLevelControllerThread-1532409819580] [timeMillis: 1532409822321] [levelValue: 800] [[
  Authorization Service has successfully initialized.]]

[2018-07-24T10:53:42.382+0530] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1532409818457] [timeMillis: 1532409822382] [levelValue: 800] [[
  Grizzly Framework 2.3.31 started in: 197ms - bound to [/0.0.0.0:8080]]]

[2018-07-24T10:53:42.615+0530] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1532409818457] [timeMillis: 1532409822615] [levelValue: 800] [[
  Grizzly Framework 2.3.31 started in: 41ms - bound to [/0.0.0.0:8181]]]

[2018-07-24T10:53:42.667+0530] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1532409818457] [timeMillis: 1532409822667] [levelValue: 800] [[
  Grizzly Framework 2.3.31 started in: 32ms - bound to [/0.0.0.0:4848]]]

[2018-07-24T10:53:43.435+0530] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1532409818457] [timeMillis: 1532409823435] [levelValue: 800] [[
  Grizzly Framework 2.3.31 started in: 48ms - bound to [/0.0.0.0:3700]]]

[2018-07-24T10:53:43.809+0530] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1532409818457] [timeMillis: 1532409823809] [levelValue: 800] [[
  Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry]]

[2018-07-24T10:53:44.332+0530] [Payara 4.1] [INFO] [] [org.glassfish.ha.store.spi.BackingStoreFactoryRegistry] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1532409818394] [timeMillis: 1532409824332] [levelValue: 800] [[
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry]]

[2018-07-24T10:53:44.339+0530] [Payara 4.1] [INFO] [] [fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactory] [tid: _ThreadID=15 _ThreadName=RunLevelControllerThread-1532409818394] [timeMillis: 1532409824339] [levelValue: 800] [[
  Registered Hazelcast BackingStoreFactory with persistence-type = hazelcast]]

[2018-07-24T10:53:45.686+0530] [Payara 4.1] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1532409825686] [levelValue: 800] [[
  Payara Server Blue  4.1.2.181 #badassfish (220) startup time : Felix (13,803ms), startup services(7,321ms), total(21,124ms)]]

[2018-07-24T10:53:45.692+0530] [Payara 4.1] [INFO] [] [fish.payara.nucleus.notification.NotificationService] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1532409825692] [levelValue: 800] [[
  Payara Notification Service bootstrapped with configuration: NotificationExecutionOptions{enabled=true, notifierConfigurationExecutionOptionsList={LOG=LogNotifierConfigurationExecutionOptions{useSeparateLogFile=false} NotifierConfigurationExecutionOptions{notifierType=LOG, enabled=true}}}]]

[2018-07-24T10:53:45.870+0530] [Payara 4.1] [INFO] [] [fish.payara.nucleus.util.CleanupPostBoot] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1532409825870] [levelValue: 800] [[
  Cleaning JarFileFactory Cache to prevent jar FD leaks]]

[2018-07-24T10:53:47.489+0530] [Payara 4.1] [INFO] [NCLS-JMX-00005] [javax.enterprise.system.jmx] [tid: _ThreadID=60 _ThreadName=Thread-15] [timeMillis: 1532409827489] [levelValue: 800] [[
  JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://0.0.0.0:8686/jndi/rmi://0.0.0.0:8686/jmxrmi]]

[2018-07-24T10:53:47.918+0530] [Payara 4.1] [INFO] [NCLS-CORE-00087] [javax.enterprise.system.core] [tid: _ThreadID=17 _ThreadName=RunLevelControllerThread-1532409818456] [timeMillis: 1532409827918] [levelValue: 800] [[
  Grizzly Framework 2.3.31 started in: 16ms - bound to [/0.0.0.0:7676]]]

[2018-07-24T10:53:47.932+0530] [Payara 4.1] [INFO] [NCLS-BOOTSTRAP-00027] [javax.enterprise.bootstrap] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1532409827932] [levelValue: 800] [[
  Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@9d3d54e as OSGi service registration: org.apache.felix.framework.ServiceRegistrationImpl@71789580.]]

[2018-07-24T10:53:48.828+0530] [Payara 4.1] [INFO] [] [] [tid: _ThreadID=12 _ThreadName=FelixStartLevel] [timeMillis: 1532409828828] [levelValue: 800] [[
  /opt/payara41/glassfish/domains/domain1/autodeploy/bundles does not exist, please create it.]]

[2018-07-24T10:54:08.159+0530] [Payara 4.1] [INFO] [AS-WEB-GLUE-00198] [javax.enterprise.web] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409848159] [levelValue: 800] [[
  Created HTTP listener http-listener-1 on host/port 0.0.0.0:8080]]

[2018-07-24T10:54:08.201+0530] [Payara 4.1] [INFO] [AS-WEB-GLUE-00198] [javax.enterprise.web] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409848201] [levelValue: 800] [[
  Created HTTP listener http-listener-2 on host/port 0.0.0.0:8181]]

[2018-07-24T10:54:08.214+0530] [Payara 4.1] [INFO] [AS-WEB-GLUE-00198] [javax.enterprise.web] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409848214] [levelValue: 800] [[
  Created HTTP listener admin-listener on host/port 0.0.0.0:4848]]

[2018-07-24T10:54:08.340+0530] [Payara 4.1] [INFO] [AS-WEB-GLUE-00200] [javax.enterprise.web] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409848340] [levelValue: 800] [[
  Created virtual server server]]

[2018-07-24T10:54:08.375+0530] [Payara 4.1] [INFO] [AS-WEB-GLUE-00200] [javax.enterprise.web] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409848375] [levelValue: 800] [[
  Created virtual server __asadmin]]

[2018-07-24T10:54:09.350+0530] [Payara 4.1] [INFO] [] [javax.enterprise.resource.corba.org.glassfish.enterprise.iiop.api] [tid: _ThreadID=47 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1532409849350] [levelValue: 800] [[
  GlassFishORBFactory service initialized.]]

[2018-07-24T10:54:09.716+0530] [Payara 4.1] [INFO] [AS-WEB-CORE-00306] [javax.enterprise.web.core] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409849716] [levelValue: 800] [[
  Setting JAAS app name glassfish-web]]

[2018-07-24T10:54:09.737+0530] [Payara 4.1] [INFO] [AS-WEB-GLUE-00201] [javax.enterprise.web] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409849737] [levelValue: 800] [[
  Virtual server server loaded default web module ]]

[2018-07-24T10:54:13.466+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01002] [javax.enterprise.system.core.security] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409853466] [levelValue: 800] [[
  Java security manager is disabled.]]

[2018-07-24T10:54:13.486+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01010] [javax.enterprise.system.core.security] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409853486] [levelValue: 800] [[
  Entering Security Startup Service.]]

[2018-07-24T10:54:13.492+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01143] [javax.enterprise.system.core.security] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409853492] [levelValue: 800] [[
  Loading policy provider com.sun.enterprise.security.provider.PolicyWrapper.]]

[2018-07-24T10:54:14.071+0530] [Payara 4.1] [INFO] [NCLS-SECURITY-01011] [javax.enterprise.system.core.security] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409854071] [levelValue: 800] [[
  Security Service(s) started successfully.]]

[2018-07-24T10:54:14.693+0530] [Payara 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409854693] [levelValue: 1000] [[
  Exception while deploying the app [__admingui]]]

[2018-07-24T10:54:14.698+0530] [Payara 4.1] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409854698] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.ExceptionInInitializerError
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.<init>(XMLSchemaValidator.java:1130)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.configurePipeline(XML11Configuration.java:1206)
	at com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.configurePipeline(XIncludeAwareParserConfiguration.java:156)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:812)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:321)
	at com.sun.enterprise.deployment.io.DeploymentDescriptorFile.read(DeploymentDescriptorFile.java:248)
	at com.sun.enterprise.deployment.archivist.Archivist.readStandardDeploymentDescriptor(Archivist.java:677)
	at com.sun.enterprise.deployment.archivist.Archivist.readDeploymentDescriptors(Archivist.java:389)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:269)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:278)
	at com.sun.enterprise.deployment.archivist.Archivist.open(Archivist.java:239)
	at com.sun.enterprise.deployment.archivist.ApplicationFactory.openArchive(ApplicationFactory.java:161)
	at org.glassfish.javaee.core.deployment.DolProvider.processDOL(DolProvider.java:199)
	at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:223)
	at org.glassfish.javaee.core.deployment.DolProvider.load(DolProvider.java:91)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.loadDeployer(ApplicationLifecycle.java:882)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.setupContainerInfos(ApplicationLifecycle.java:822)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:379)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:406)
	at com.sun.enterprise.v3.admin.adapter.InstallerThread.load(InstallerThread.java:211)
	at com.sun.enterprise.v3.admin.adapter.InstallerThread.run(InstallerThread.java:100)
Caused by: com.sun.org.apache.xerces.internal.impl.dv.DVFactoryException: Schema factory class com.sun.org.apache.xerces.internal.impl.dv.xs.SchemaDVFactoryImpl does not extend from SchemaDVFactory.
	at com.sun.org.apache.xerces.internal.impl.dv.SchemaDVFactory.getInstance(SchemaDVFactory.java:75)
	at com.sun.org.apache.xerces.internal.impl.dv.SchemaDVFactory.getInstance(SchemaDVFactory.java:57)
	at com.sun.org.apache.xerces.internal.impl.xs.SchemaGrammar$BuiltinSchemaGrammar.<init>(SchemaGrammar.java:278)
	at com.sun.org.apache.xerces.internal.impl.xs.SchemaGrammar.<clinit>(SchemaGrammar.java:1296)
	... 26 more
]]

[2018-07-24T10:54:15.507+0530] [Payara 4.1] [SEVERE] [NCLS-CORE-00041] [javax.enterprise.system.core] [tid: _ThreadID=87 _ThreadName=Thread-21] [timeMillis: 1532409855507] [levelValue: 1000] [[
  Application deployment failed: Exception while deploying the app [__admingui]]]

[2018-07-24T10:54:18.223+0530] [Payara 4.1] [INFO] [NCLS-REST-00001] [javax.enterprise.admin.rest] [tid: _ThreadID=47 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1532409858223] [levelValue: 800] [[
  Listening to REST requests at context: /management/domain.]]

**Comment by DRDL** [comment]
Kindly revert back as soon as possible

**Comment by mguimard** [comment]
You are using payara blue (for IBM sdk). We don't bring support either. 
You have to use fish.payara.distributions:payara:4.1.2.181

**Comment by DRDL** [comment]
Can you share the link please from where i need to download the webserver

**Comment by mguimard** [comment]
The URL was missing in the installation guide. Please find the payara archive URL under https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide

**Comment by DRDL** [comment]
I have removed all the old stuff in /opt directory and started with new. Thank you its working
