### ISSUE TITLE
Mail Notification failled after workspaces deletion

### ISSUE THREAD

**Issue by ludoBarel** [docdoku/docdoku-plm#1183]
I've tried to delete workspace with the web application, then sever side  an exception was raised :

`[2018-08-20T14:37:59.565+0200] [Payara 4.1] [GRAVE] [] [org.polarsys.eplmp.server.NotifierBean] [tid: _ThreadID=102 _ThreadName=__ejb-thread-pool10] [timeMillis: 1534768679565] [levelValue: 1000] [[
  Message format error. 
	Mail can't be sent. 
	Couldn't connect to host, port: test@docdoku.com, 25; timeout -1
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: ludovic.barel@docdoku.com, 25; timeout -1;
  nested exception is:
	java.net.UnknownHostException: ludovic.barel@docdoku.com
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
	at javax.mail.Service.connect(Service.java:366)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.polarsys.eplmp.server.NotifierBean.sendEmail(NotifierBean.java:709)
	at org.polarsys.eplmp.server.NotifierBean.sendMessage(NotifierBean.java:654)
	at org.polarsys.eplmp.server.NotifierBean.sendWorkspaceDeletionNotification(NotifierBean.java:249)`

**Comment by ludoBarel** [comment]
Seems to be normal because i didn't have any server Mail running on localhost. So i've used a [fake server](http://nilhcem.com/FakeSMTP/) for tests.
