### ISSUE TITLE
Erreur à l'installation de docdoku avec maven

### ISSUE THREAD

**Issue by ytuquet** [docdoku/docdoku-plm#1204]
I have a problem when i launch mvn install : 

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.docdoku:docdoku-api-java:jar:2.5.2-SNAPSHOT
[WARNING] 'profiles.profile[running-instance].plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-surefire-plugin @ com.docdoku:docdoku-api-java:[unknown-version], /home/canon/docdoku-plm/docdoku-api-java/pom.xml, line 332, column 29
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] docdoku-plm DocDokuPLM
[INFO] docdoku-api
[INFO] docdoku-api-java
[INFO] docdoku-api-js
[INFO] docdoku-cli Command Line Interface
[INFO] Converter for COLLADA files
[INFO] converter-dae-ejb
[INFO] converter-dae-ear
[INFO] All Converter
[INFO] converter-all-ejb
[INFO] converter-all-ear
[INFO] IFC Converter
[INFO] converter-ifc-ejb
[INFO] converter-ifc-ear
[INFO] Wavefront OBJ Converter
[INFO] converter-obj-ejb
[INFO] converter-obj-ear
[INFO] STEP Converter
[INFO] converter-step-ejb
[INFO] converter-step-ear
[INFO] Attributes importer
[INFO] importer-attributes-ejb
[INFO] importer-attributes-ear
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building docdoku-plm DocDokuPLM 2.5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ docdoku-plm ---
[INFO] Installing /home/canon/docdoku-plm/pom.xml to /root/.m2/repository/com/docdoku/docdoku-plm/2.5.2-SNAPSHOT/docdoku-plm-2.5.2-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building docdoku-api 2.5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.polarsys.eplmp:eplmp-server-rest:jar:sources:2.5.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] docdoku-plm DocDokuPLM ............................. SUCCESS [  0.198 s]
[INFO] docdoku-api ........................................ FAILURE [  0.402 s]
[INFO] docdoku-api-java ................................... SKIPPED
[INFO] docdoku-api-js ..................................... SKIPPED
[INFO] docdoku-cli Command Line Interface ................. SKIPPED
[INFO] Converter for COLLADA files ........................ SKIPPED
[INFO] converter-dae-ejb .................................. SKIPPED
[INFO] converter-dae-ear .................................. SKIPPED
[INFO] All Converter ...................................... SKIPPED
[INFO] converter-all-ejb .................................. SKIPPED
[INFO] converter-all-ear .................................. SKIPPED
[INFO] IFC Converter ...................................... SKIPPED
[INFO] converter-ifc-ejb .................................. SKIPPED
[INFO] converter-ifc-ear .................................. SKIPPED
[INFO] Wavefront OBJ Converter ............................ SKIPPED
[INFO] converter-obj-ejb .................................. SKIPPED
[INFO] converter-obj-ear .................................. SKIPPED
[INFO] STEP Converter ..................................... SKIPPED
[INFO] converter-step-ejb ................................. SKIPPED
[INFO] converter-step-ear ................................. SKIPPED
[INFO] Attributes importer ................................ SKIPPED
[INFO] importer-attributes-ejb ............................ SKIPPED
[INFO] importer-attributes-ear ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.831 s
[INFO] Finished at: 2019-02-01T13:26:23+01:00
[INFO] Final Memory: 16M/175M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project docdoku-api: Could not resolve dependencies for project com.docdoku:docdoku-api:jar:2.5.2-SNAPSHOT: The following artifacts could not be resolved: org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT, org.polarsys.eplmp:eplmp-server-rest:jar:sources:2.5.2-SNAPSHOT: Could not find artifact org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project docdoku-api: Could not resolve dependencies for project com.docdoku:docdoku-api:jar:2.5.2-SNAPSHOT: The following artifacts could not be resolved: org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT, org.polarsys.eplmp:eplmp-server-rest:jar:sources:2.5.2-SNAPSHOT: Could not find artifact org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:128)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.docdoku:docdoku-api:jar:2.5.2-SNAPSHOT: The following artifacts could not be resolved: org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT, org.polarsys.eplmp:eplmp-server-rest:jar:sources:2.5.2-SNAPSHOT: Could not find artifact org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:212)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT, org.polarsys.eplmp:eplmp-server-rest:jar:sources:2.5.2-SNAPSHOT: Could not find artifact org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT, org.polarsys.eplmp:eplmp-server-rest:jar:sources:2.5.2-SNAPSHOT: Could not find artifact org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.polarsys.eplmp:eplmp-core:jar:2.5.2-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
        ... 27 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :docdoku-api

Does someone can help me please ?

**Comment by florentgarin** [comment]
You have to mvn install the eplmp project first at the same version. So you need to checkout the same branches (dev for DocDokuPLM, develop for eplmp).

Just follow these instructions:
https://github.com/docdoku/docdoku-plm/wiki/Software-Configuration

**Comment by ytuquet** [comment]
Thanks for your return.

I did wat tell you and I was able to install it.
Now, when I try to install docdoku front web, I have a new problem. I opened a ticket on:
https://github.com/docdoku/docdoku-web-front/issues ticket number 83

the command npm run dev bloking on:
Running "watch: dev" (watch) task
Waiting...

Thank you again for your help.
