### ISSUE TITLE
Work-space not getting created

### ISSUE THREAD

**Issue by nikilmethew** [docdoku/docdoku-plm#1206]
**Note**: Installed from Docker.

After the creation of Workspace(eg: Test).

 The following Https request is made. 

**Request URL**: https://docdokuplm.local:10081/eplmp-server-rest/api/workspaces/Test/stats-overview

**Request Method**: GET

**Status Code**: 404 Not Found

**Remote Address**: 127.0.0.1:10081

**Response**: The workspace "Test" or its sub-elements have not been found

Why I'm I getting this error.

and when calling Health API I'm getting this 500 error.

**URL**: https://docdokuplm.local:10081/eplmp-server-rest/api/platform/health
(https://prnt.sc/mf70de)

Getting many 404 Not Found.

What might be the possible reason Is this related to Nginx ? How to overcome this 404 Not Found errors.

![404](https://user-images.githubusercontent.com/46815046/52203339-06287c00-2897-11e9-8193-7d416f157a50.png)

**Comment by nikilmethew** [comment]
Below is my Log during creating new Workspace

```
back_1       | [#|2019-02-11T05:24:16.761+0000|WARNING|Payara 4.1|org.polarsys.eplmp.server.indexer.IndexerManagerBean|_ThreadID=33;_ThreadName=http-thread-pool::http-listener-1(1);_TimeMillis=1549862656761;_LevelValue=900;|
back_1       |   Cannot create index for workspace [Test2]
back_1       | Sorry the indexer server appears to be unreachable
back_1       | 	at org.polarsys.eplmp.server.indexer.IndexManagerBean.indexExists(IndexManagerBean.java:219)
back_1       | 	at org.polarsys.eplmp.server.indexer.IndexManagerBean.indicesExist(IndexManagerBean.java:208)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
back_1       | 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
back_1       | 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4836)
back_1       | 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
back_1       | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
back_1       | 	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
back_1       | 	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
back_1       | 	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
back_1       | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
back_1       | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
back_1       | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
back_1       | 	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
back_1       | 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
back_1       | 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4808)
back_1       | 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4796)
back_1       | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
back_1       | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
back_1       | 	at com.sun.proxy.$Proxy428.indicesExist(Unknown Source)
back_1       | 	at org.polarsys.eplmp.server.indexer.__EJB31_Generated__IndexManagerBean__Intf____Bean__.indicesExist(Unknown Source)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433)
back_1       | 	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:133)
back_1       | 	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
back_1       | 	at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:67)
back_1       | 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
back_1       | 	at org.polarsys.eplmp.server.indexer.IndexManagerBean$Proxy$_$$_Weld$EnterpriseProxy$.indicesExist(Unknown Source)
back_1       | 	at org.polarsys.eplmp.server.indexer.IndexerManagerBean.createWorkspaceIndex(IndexerManagerBean.java:120)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
back_1       | 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
back_1       | 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4836)
back_1       | 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
back_1       | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
back_1       | 	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
back_1       | 	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
back_1       | 	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
back_1       | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
back_1       | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
back_1       | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
back_1       | 	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
back_1       | 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
back_1       | 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4808)
back_1       | 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4796)
back_1       | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
back_1       | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
back_1       | 	at com.sun.proxy.$Proxy403.createWorkspaceIndex(Unknown Source)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433)
back_1       | 	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:133)
back_1       | 	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
back_1       | 	at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:67)
back_1       | 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
back_1       | 	at org.polarsys.eplmp.server.indexer.IIndexerManagerLocal$253284610$Proxy$_$$_Weld$EnterpriseProxy$.createWorkspaceIndex(Unknown Source)
back_1       | 	at org.polarsys.eplmp.server.WorkspaceManagerBean.createWorkspace(WorkspaceManagerBean.java:160)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
back_1       | 	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
back_1       | 	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4836)
back_1       | 	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
back_1       | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
back_1       | 	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
back_1       | 	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
back_1       | 	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
back_1       | 	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
back_1       | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
back_1       | 	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
back_1       | 	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
back_1       | 	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
back_1       | 	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
back_1       | 	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4808)
back_1       | 	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4796)
back_1       | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
back_1       | 	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
back_1       | 	at com.sun.proxy.$Proxy393.createWorkspace(Unknown Source)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433)
back_1       | 	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:133)
back_1       | 	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
back_1       | 	at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:67)
back_1       | 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
back_1       | 	at org.polarsys.eplmp.server.IWorkspaceManagerLocal$2140218957$Proxy$_$$_Weld$EnterpriseProxy$.createWorkspace(Unknown Source)
back_1       | 	at org.polarsys.eplmp.server.rest.WorkspaceResource.createWorkspace(WorkspaceResource.java:429)
back_1       | 	at org.polarsys.eplmp.server.rest.WorkspaceResource$Proxy$_$$_WeldClientProxy.createWorkspace(Unknown Source)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
back_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
back_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
back_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
back_1       | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
back_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
back_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
back_1       | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
back_1       | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
back_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
back_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
back_1       | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
back_1       | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
back_1       | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
back_1       | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
back_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
back_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
back_1       | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
back_1       | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
back_1       | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
back_1       | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
back_1       | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
back_1       | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
back_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
back_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
back_1       | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
back_1       | 	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1692)
back_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
back_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
back_1       | 	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
back_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
back_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
back_1       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
back_1       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
back_1       | 	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
back_1       | 	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:598)
back_1       | 	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
back_1       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
back_1       | 	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
back_1       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
back_1       | 	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
back_1       | 	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
back_1       | 	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
back_1       | 	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
back_1       | 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
back_1       | 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
back_1       | 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
back_1       | 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
back_1       | 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
back_1       | 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
back_1       | 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
back_1       | 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
back_1       | 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
back_1       | 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
back_1       | 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
back_1       | 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
back_1       | 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
back_1       | 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
back_1       | 	at java.lang.Thread.run(Thread.java:748)
back_1       | |#]
back_1       | 
proxy_1      | 172.18.0.1 - - [11/Feb/2019:05:24:16 +0000] "POST /eplmp-server-rest/api/workspaces HTTP/1.1" 200 72 "https://docdokuplm.local:10081/workspace-management/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36" "-"
proxy_1      | 172.18.0.1 - - [11/Feb/2019:05:24:16 +0000] "GET /eplmp-server-rest/api/workspaces/reachable-users HTTP/1.1" 200 2 "https://docdokuplm.local:10081/workspace-management/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36" "-"
back_1       | [#|2019-02-11T05:24:16.855+0000|WARNING|Payara 4.1|org.polarsys.eplmp.server.rest.exceptions.mapper.NotFoundExceptionMapper|_ThreadID=34;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1549862656855;_LevelValue=900;|
back_1       |   The workspace "Test2" or its sub-elements have not been found|#]
back_1       | 
proxy_1      | 172.18.0.1 - - [11/Feb/2019:05:24:16 +0000] "GET /eplmp-server-rest/api/workspaces/Test2/stats-overview HTTP/1.1" 404 61 "https://docdokuplm.local:10081/workspace-management/index.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36" "-"
kibana_1     | {"type":"log","@timestamp":"2019-02-11T05:24:18Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://es:9200/"}
kibana_1     | {"type":"log","@timestamp":"2019-02-11T05:24:18Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}

```

**Comment by florentgarin** [comment]
Seems that Elasticsearch is not properly installed or configured.
Follow instructions bellow:
https://github.com/docdoku/docdoku-plm/wiki/Installation-Guide
