### ISSUE TITLE
[OfficeDocument] Some pdf can't be open in permalink

### ISSUE THREAD

**Issue by TaylorHub** [docdoku/docdoku-plm#318]
iTextPdf failed to edit some pdf (merge a page with the remanderof the pdf). It  occur when the pdf is encrypted and you didn't provide the owner password. 

```
java.lang.IllegalArgumentException: PdfReader not opened with owner password
at com.itextpdf.text.pdf.PdfReaderInstance.getImportedPage(PdfReaderInstance.java:81)
at com.itextpdf.text.pdf.PdfCopy.getImportedPageImpl(PdfCopy.java:377)
at com.itextpdf.text.pdf.PdfCopy.getImportedPage(PdfCopy.java:244)
at com.docdoku.server.extras.TitleBlockGenerator.mergePdfDocuments(TitleBlockGenerator.java:80)
```

**Comment by mguimard** [comment]
Itext has been replaced with pdfbox.
