### ISSUE TITLE
Error while updating access rights for documents 

### ISSUE THREAD

**Issue by chadidas** [docdoku/docdoku-plm#350]
create new document in a workspace where the user belong to a group that has full access in that workspace.(for instance user:demo, workspace001)
checkin the document
select the document and click on the button of acess right management 
update rights of other users 
click on save => Error on update ACL 
logs:

         EJB5184:A system exception occurred during an invocation on EJB DocumentResource, method: public javax.ws.rs.core.Response com.docdoku.server.rest.DocumentResource.updateACL(java.lang.String,java.lang.String,java.lang.String,com.docdoku.server.rest.dto.ACLDTO)]]
        javax.ejb.EJBException
                at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
                at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
                at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
                at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4475)
                at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2009)
                at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:1979)
                at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
                at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
                at com.sun.proxy.$Proxy367.updateACL(Unknown Source)
                at com.docdoku.server.rest.__EJB31_Generated__DocumentResource__Intf____Bean__.updateACL(Unknown Source)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

**Comment by mguimard** [comment]
Duplicated #349
