### ISSUE TITLE
[Document constraint] Delete document with change items

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#399]
Try to delete a folder that contains an document linked to a change item. The document disapears and no error feedback. Transaction is rolled back.
    
[2015-01-27T17:12:33.640+0100] [glassfish 4.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=53 _ThreadName=http-listener-1(5)] [timeMillis: 1422375153640] [levelValue: 900] [[
  StandardWrapperValve[com.docdoku.server.rest.ApplicationConfig]: Servlet.service() for servlet com.docdoku.server.rest.ApplicationConfig threw exception
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`docdokuplm`.`CHANGEORDER_AFFECTED_DOCUMENT`, CONSTRAINT `FK_CHANGEORDER_AFFECTED_DOCUMENT_ITERATION` FOREIGN KEY (`ITERATION`, `DOCUMENTMASTER_WORKSPACE_ID`, `DOCUMENTREVISION_VERSION`, `DOCU)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)

**Comment by mguimard** [comment]
Closed by d2f9b071f1453aa6d5d34ebdab2c1a3a74efd889
