### ISSUE TITLE
[ModificationNotification] display on product list

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#733]
Bug happen when part has no iteration (not yet, still iteration 1 checked out).

Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.docdoku.server.ProductManagerBean$10.onPathWalk(ProductManagerBean.java:2959)
	at com.docdoku.server.configuration.PSFilterVisitor.visit(PSFilterVisitor.java:162)
	at com.docdoku.server.configuration.PSFilterVisitor.startVisit(PSFilterVisitor.java:156)
	at com.docdoku.server.configuration.PSFilterVisitor.<init>(PSFilterVisitor.java:61)
	at com.docdoku.server.ProductManagerBean$10.<init>(ProductManagerBean.java:2927)
	at com.docdoku.server.ProductManagerBean.hasModificationNotification(ProductManagerBean.java:2927)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by mguimard** [comment]
Walking through product structures can be really heavy in case of big trees. We should have a notification state at the configuration item level. However, dismissing it programmatically would be also resource consuming as it would require to walk through it again.
