### ISSUE TITLE
[Indexing content] Fail to index excel file 

### ISSUE THREAD

**Issue by mguimard** [docdoku/docdoku-plm#775]
When indexing excel files,  we have some errors in the logs :

    Caused by: java.lang.NullPointerException
        at org.apache.poi.hssf.usermodel.HSSFComment.getColumn(HSSFComment.java:167)
        at org.apache.poi.hssf.usermodel.HSSFSheet.lookForComment(HSSFSheet.java:2108)
        at org.apache.poi.hssf.usermodel.HSSFSheet.findCellComment(HSSFSheet.java:2093)
        at org.apache.poi.hssf.usermodel.HSSFCell.getCellComment(HSSFCell.java:1017)
        at org.apache.poi.hssf.extractor.ExcelExtractor.getText(ExcelExtractor.java:388)
        at com.docdoku.server.esindexer.ESTools.microsoftExelDocumentToString(ESTools.java:244)

**Comment by mguimard** [comment]
Happens on 2007+ excel files with "xls" extension.
