### ISSUE TITLE
[Saving Product Instance] generates NPEx

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#804]
Caused by: java.lang.NullPointerException
	at com.docdoku.core.configuration.ProductBaseline.getBaselinedDocuments(ProductBaseline.java:169)
	at com.docdoku.server.products.ProductInstanceManagerBean.updateProductInstance(ProductInstanceManagerBean.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4695)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:630)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:582)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java
:46)

**Comment by florentgarin** [comment]
Ok, that's probably because of data issue, we should check if the data has been migrated in production.
