### ISSUE TITLE
[indexation] failed on some documents

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#816]
org.apache.poi.POIXMLException: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Package should contain a content type part [M1.13]
	at org.apache.poi.util.PackageHelper.open(PackageHelper.java:41)
	at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:120)
	at com.docdoku.server.esindexer.ESTools.microsoftXMLWordDocumentToString(ESTools.java:233)
	at com.docdoku.server.esindexer.ESTools.streamToString(ESTools.java:159)
	at com.docdoku.server.esindexer.ESIndexer.indexRequest(ESIndexer.java:511)
	at com.docdoku.server.esindexer.ESIndexer.bulkDocumentsIndexRequestBuilder(ESIndexer.java:485)

**Comment by florentgarin** [comment]
not relevant file is empty
