### ISSUE TITLE
[Query builder] issue when selecting "checkin date"

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-plm#843]
![capture du 2015-11-16 11-49-50](https://cloud.githubusercontent.com/assets/868602/11180708/408ff230-8c5d-11e5-9370-6e4f5ef2f709.png)

**Comment by mguimard** [comment]
Server trace

    Caused by: java.lang.IllegalArgumentException: The attribute [checkinDate] is not present in the managed type [EntityTypeImpl@1506377670:PartRevision [ javaType: class com.docdoku.core.product.PartRevision descriptor: RelationalDescriptor(com.docdoku.core.product.PartRevision --> [DatabaseTable(PARTREVISION)]), mappings: 19]].
	at org.eclipse.persistence.internal.jpa.metamodel.ManagedTypeImpl.getAttribute(ManagedTypeImpl.java:148)
	at org.eclipse.persistence.internal.jpa.querydef.FromImpl.get(FromImpl.java:309)
	at com.docdoku.server.dao.QueryDAO.getPartRevisionPredicate(QueryDAO.java:275)
	at com.docdoku.server.dao.QueryDAO.getRulePredicate(QueryDAO.java:227)
	at com.docdoku.server.dao.QueryDAO.getPredicate(QueryDAO.java:211)
	at com.docdoku.server.dao.QueryDAO.getPredicate(QueryDAO.java:197)
	at com.docdoku.server.dao.QueryDAO.runQuery(QueryDAO.java:146)
	at com.docdoku.server.ProductManagerBean.searchPartRevisions(ProductManagerBean.java:2586)
	at sun.reflect.GeneratedMethodAccessor2228.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4695)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:630)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:582)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:582)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4667)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4655)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 93 more
