### ISSUE TITLE
[Group delete] from workspace

### ISSUE THREAD

**Issue by elisabelgenereux** [docdoku/docdoku-plm#923]
Scenario:

- Create an account
- Create a workspace
- Create another account, add it to the workspace
- Add 4 groups
- In one group, add the 2 users
- Create a document and create ACL on it
- Try to delete the group with the 2 users

Sometimes you receive an unhandled error instead of the error "You cannot delete a group which has ACL on documents or parts".

Unhandled error received:

Exception Description: A null value can not be used as a key in a container of type [class java.util.Hashtable]. Ensure your key values for the objects of type [class com.docdoku.core.security.ACLUserGroupEntry] can not be null.

Stack trace:

[#|2016-02-05T16:31:31.602+0100|WARNING|glassfish 4.0|org.eclipse.persistence.session.file:/Applications/glassfish4.0/glassfish/domains/docdokuplm-payment/applications/docdoku-server-ear/docdoku-server-ejb_jar/_DocDoku-PU|_ThreadID=22;_ThreadName=http-listener-1(1);_TimeMillis=1454686291602;_LevelValue=900;|
 Local Exception Stack: 
Exception [EclipseLink-6150] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.ValidationException
Exception Description: A null value can not be used as a key in a container of type [class java.util.Hashtable]. Ensure your key values for the objects of type [class com.docdoku.core.security.ACLUserGroupEntry] can not be null.
at org.eclipse.persistence.exceptions.QueryException.mapKeyIsNull(QueryException.java:797)
at org.eclipse.persistence.internal.queries.MapContainerPolicy.addInto(MapContainerPolicy.java:144)
at org.eclipse.persistence.internal.queries.ContainerPolicy.addInto(ContainerPolicy.java:140)
at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObjectsInto(ObjectBuilder.java:1182)
at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:497)
at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1155)
at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1114)
at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:402)
at org.eclipse.persistence.internal.sessions.AbstractSession.internalExecuteQuery(AbstractSession.java:3207)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1797)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1779)
at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.valueFromQuery(NoIndirectionPolicy.java:326)

**Comment by mguimard** [comment]
Cannot reproduce, seems corrected since jsp pages migration. Reopen if needed
